### ISSUE TITLE
May I ask about the implementation for the swift framework?

### ISSUE THREAD

**Issue by charlieop** [dinhonms/Lab-Unity-App#1]
I am trying to develop a unity app, and it requires some native iOS feature. 
I need a way to call swift function, and the swift functions should be able to call back to unity.

My code and plugin structure looks very similar to yours, but I don't know how to write the swift part.

Here is my email: charlieop01@gamil.com

Thank you in advance!

**Comment by dinhonms** [comment]
I'll reach you out to take a look at your needs and whther I can help you or not.

**Comment by charlieop** [comment]
Thank you for your reply! Since I have not yet received your email, I'll just state my question here:

### Goal:
I am trying to build a unity app that can have two-way communication with the native code, so that I can use the WatchConnectivity toolkit to talk to an apple watch from unity. 
Since I am new to both app development, I have no experience in Objective-C, so I want to write the native code purely in Swift.

### Issue:
I have build a Unity3D plugin using the Xcode framework, and is able to call native swift functions from unity. However, I am having trouble to call function back from native to unity. Unity document stated there are 2 ways to callback, one is using UnitySendMessage(), but since I build the framework before putting it into Unity, XCode is unable to compile and build. 
_Do you happen to know how to solve this?_

So I go for the function delegate way, which seems to be the way you are doing it. I can understand the code part in c#, create a function delegate and pass it through the function called. **But I don't know what is the corresponding part in swift.**  I assume that I should have a parameter that receives the delegate function's pointer, but what should be it's type in swift? And how should I call the function delegate? 
_May I have a look for the Xcode project for the IOS plugin?_

**Comment by dinhonms** [comment]
You can take a look at the Xcode project here https://github.com/dinhonms/Swift-Unity-Plugin. Maybe  you can show the c# methods so that I can try help you when I find some time(my time is limited nowadays).

**Comment by charlieop** [comment]
Yes I have already downloaded that and checked, however it does _not_ contain the part where it receives a delegate function pointer and then calls it. 

Can you please send me the Xcode project for this app?

Thank you very much for your time!

**Comment by charlieop** [comment]
The C# method looks like this:
```
// in a class

public delegate void CallBackFunction(string value);

[DllImport("__Internal")]
public static extern void _callNativeFunction(string value, CallBackFunction functionDelegate);

public static void callNativeFunction(string value, CallBackFunction functionDelegate)
{
    _callNativeFunction(value: value, functionDelegate: functionDelegate);
}

[MonoPInvokeCallback(typeof(CallBackFunction))]
private static void functionDelegateSentToSwift(string message)
{
    Debug.Log("Info get: {message}");
}


public void onButtonPressed() 
{
    callNativeFunction(value: "HI from Unity to Swift", functionDelegate: functionDelegateSentToSwift)
}


```

How should I write the function parameters of `_callNativeFunction` in swift? And how can I call this function in swift?

**Comment by dinhonms** [comment]
You should write as
 ```
func _callNativeFunction(value: UnsafePointer <CChar>, funcCallback: @convention(c) @escaping (String) -> Void){
       funcCallback = Somewhere.yourCallback
}
```

//put this somewhere
`    public var yourCallback: ((String) -> Void)?`

//call the callback passing the string value
```
//this function should be called somewhere in your swift logic
func example(){
      yourCallback("your` value")
}
```


That's the source code fo the plugin used in this repository https://github.com/dinhonms/Save-Media-To-Gallery.

**Comment by charlieop** [comment]
Thank you for your help!

**Comment by charlieop** [comment]
Thank you for your help! It works very well for me. 

It seems that I also have to change the function parameter from `(String) -> Void` to `(UnsafePointer<Char>) -> Void` so that it can correctly pass the string back to c#.

Since I am still learning these, if you have time, may I know where can you find all the correspondence? such as: 

`string in c#` is `UnsafePointer<Char> in swift`
`functionDelegate in c#` is `@convention(c) (String) -> Void in swift`
and etc...

**Comment by dinhonms** [comment]
Take a look at this file https://github.com/dinhonms/Save-Media-To-Gallery/blob/main/SaveMediaToGallery/UnityBridge.swift, for the  correspondences
